---
- name: playbook to build our docker image
  hosts: 172.31.3.17
  tasks:
    - name: remove existing bashscripts directory and ignore task if bashscripts folder is not there
      ansible.builtin.shell:
        cmd: sudo rm -rf bashscripts
      ignore_errors: yes

    - name: create new bashscripts directory
      ansible.builtin.shell:
        cmd: sudo mkdir bashscripts

    - name: clone bashscripts repo into server
      ansible.builtin.shell:
        cmd: sudo git clone https://github.com/pvkraja227/Commerce-website
        chdir: bashscripts/

    - name: giving ownership to build.sh and giving permissions to build.sh
      ansible.builtin.shell:
        cmd: sudo chown ubuntu build.sh && sudo chmod 744 build.sh
        chdir: bashscripts/Commerce-website/project-files

    - name: running script to make build
      ansible.builtin.shell:
        cmd: ./build.sh
        chdir: bashscripts/Commerce-website/project-files
